### ISSUE TITLE
Error in getActivityTextWithoutMentions (teamsContext.js)

### ISSUE THREAD

**Issue by Sn00z3r** [OfficeDev/BotBuilder-MicrosoftTeams-node#17]
I'm writing a echo bot in normal nodejs javascript, noticed that after the first echo the following error occurs:
`TypeError: Cannot read property 'filter' of undefined
    at TeamsContext.getActivityTextWithoutMentions (F:\Programming\Repos\CHATBOT_TEAMS\testbot\node_modules\botbuilder-teams\lib\teamsContext.js:113:52)
    at Object.onMessage (F:\Programming\Repos\CHATBOT_TEAMS\testbot\bot.js:24:43)
    at TeamsActivityProcessor.<anonymous> (F:\Programming\Repos\CHATBOT_TEAMS\testbot\node_modules\botbuilder-teams\lib\activityProcessor\teamsActivityProcessor.js:130:35)
    at Generator.next (<anonymous>)
    at F:\Programming\Repos\CHATBOT_TEAMS\testbot\node_modules\botbuilder-teams\lib\activityProcessor\teamsActivityProcessor.js:29:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Programming\Repos\CHATBOT_TEAMS\testbot\node_modules\botbuilder-teams\lib\activityProcessor\teamsActivityProcessor.js:25:12)
    at TeamsActivityProcessor.processOnMessageActivity (F:\Programming\Repos\CHATBOT_TEAMS\testbot\node_modules\botbuilder-teams\lib\activityProcessor\teamsActivityProcessor.js:119:16)
    at TeamsActivityProcessor.<anonymous> (F:\Programming\Repos\CHATBOT_TEAMS\testbot\node_modules\botbuilder-teams\lib\activityProcessor\teamsActivityProcessor.js:91:36)
    at Generator.next (<anonymous>)`

I'm using the Bot Framework Emulator to test and this error is due to the fact that when sending the first ever message the activity does contain an entities key, however in subsequent messages there is no such key and this this function fails to obtain the text as the entities list is undefined:

` getActivityTextWithoutMentions() {
        
       const activity = this.turnContext.activity;

        if (activity.entities && activity.entities.length === 0) {

            return activity.text;

        }

        const recvBotId = activity.recipient.id;

        const recvBotMentioned = activity.entities.filter(e => (e.type === 'mention') && e.mentioned.id === recvBotId); // CRASH HERE

        if (recvBotMentioned.length === 0) {

            return activity.text;

        }

        let strippedText = activity.text;

        recvBotMentioned.forEach(m => m.text && (strippedText = strippedText.replace(m.text, '')));

        return strippedText.trim();

    }`

I fixed this by changing the if statement before:
`   getActivityTextWithoutMentions() {

        const activity = this.turnContext.activity;

        if ((activity.entities && activity.entities.length === 0) || activity.entities===undefined) //CHANGED IF STATEMENT {

            return activity.text;

        }

        const recvBotId = activity.recipient.id;

        const recvBotMentioned = activity.entities.filter(e => (e.type === 'mention') && e.mentioned.id === recvBotId);

        if (recvBotMentioned.length === 0) {

            return activity.text;

        }

        let strippedText = activity.text;

        recvBotMentioned.forEach(m => m.text && (strippedText = strippedText.replace(m.text, '')));

        return strippedText.trim();

    }`

Is this error due to the fact how the Bot framework emulator works, or is it an actual bug?

**Comment by billbliss** [comment]
Does it work properly in Teams (that is, does the error still occur)? The emulator doesn't work very well with Teams bots which is one of the reasons we don't recommend using it anywhere in our documentation.
