### ISSUE TITLE
Scheme dropping Mention for Entity

### ISSUE THREAD

**Issue by joshuaNathaniel** [OfficeDev/BotBuilder-MicrosoftTeams-node#19]
https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/blob/9b89ef79a120b63389c76dc072a47a8bc114ad04/botbuilder-teams-js/src/teamsContext.ts#L164

```bot.ts
onMessage: async (ctx: TurnContext) => {
  let message: Partial<Activity> = {
    type: 'message',
    textFormat: TextFormatTypes.Xml,
    text: ''
  };

  const adapter: BotFrameworkAdapter = <BotFrameworkAdapter>ctx.adapter;
  await adapter.getConversationMembers(ctx).then(async (channelAccounts: ChannelAccount[]) => {
    channelAccounts.forEach((account: ChannelAccount) => {
      message = teams.TeamsContext.addMentionToText(message as Activity, account);
    });
  });
  console.log(message);
  await ctx.sendActivity(message).catch((reason => {console.log(reason)}));
};
```

The previous code's output:

```
{ type: 'message',
    textFormat: 'xml',
    text: '<at>TestDev21</at> <at>TestDev2</at> <at>TestDev23</at>',
    entities:
  [ { type: 'mention',
    text: '<at>TestDev21</at>',
    mentioned: [Object] },
    { type: 'mention',
      text: '<at>TestDev2</at>',
      mentioned: [Object] },
    { type: 'mention',
      text: '<at>TestDev23</at>',
      mentioned: [Object] } ] }
{ Error: Invalid mention entity
  at new RestError (/Users/user/Projects/mentions/node_modules/@azure/ms-rest-js/lib/restError.ts:18:5)
  at /Users/user/Projects/mentions/node_modules/@azure/ms-rest-js/lib/policies/deserializationPolicy.ts:117:27
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 'BadArgument',
      statusCode: 400,
    request:
  WebResource {
  streamResponseBody: false,
      url: 'https://smba.trafficmanager.net/amer/v3/conversations/00000/activities/00000',
      method: 'POST',
      headers: HttpHeaders { _headersMap: [Object] },
  body: '{"type":"message","serviceUrl":"https://smba.trafficmanager.net/amer/","channelId":"msteams","from":{"id":"","name":"Imported Bot"},"conversation":{"isGroup":true,"conversationType":"groupChat","id":""},"recipient":{"id":"","name":"TestDev23","aadObjectId":""},"textFormat":"xml","text":"<at>TestDev21</at> <at>TestDev2</at> <at>TestDev23</at>","entities":[{"type":"mention"},{"type":"mention"},{"type":"mention"}],"replyToId":""}',
      query: undefined,
      formData: undefined,
      withCredentials: false,
      abortSignal: undefined,
      timeout: 0,
      onUploadProgress: undefined,
      onDownloadProgress: undefined,
      operationSpec:
  { httpMethod: 'POST',
      path: 'v3/conversations/{conversationId}/activities/{activityId}',
      urlParameters: [Array],
      requestBody: [Object],
      responses: [Object],
      serializer: [Serializer] } },
  response:
  { body: '{"error":{"code":"BadArgument","message":"Invalid mention entity"}}',
      headers: HttpHeaders { _headersMap: [Object] },
    status: 400 },
  body:
  { error: { code: 'BadArgument', message: 'Invalid mention entity' } } }
```

TeamContext.addMentionToText method works fine. Based on the remark this is a schema issue, correct? Would it be as easy as changing the schema to just extend Entity on Mention?

```botbuilder-schema::index.ts::line:1132
export interface Mention extend Entity {
  /**
   * The mentioned user
   */
  mentioned: ChannelAccount;
  /**
   * Sub Text which represents the mention (can be null or empty)
   */
  text: string;
  /**
   * Type of this entity (RFC 3987 IRI)
   */
  type: string;
}
```
I realize this is on the botbuilder project. Is there any movement on this from your end? If not I'd like to pursue some changes on this.

Looking forward to a response. :D

Cheers

**Comment by joshuaNathaniel** [comment]
Looks like my question has the [fix](https://github.com/microsoft/botbuilder-js/pull/908). I suppose I should have looked a little harder.

**Comment by joshuaNathaniel** [comment]
Need to update dependencies. 
```package.json
  "dependencies": {
    "adaptivecards": "^1.0.0",
    "botbuilder": "4.5.1",
    "botframework-connector": "4.5.1",
    "jsdom": "14.0.0"
  }
```
