### ISSUE TITLE
teams-bot sample crashes due to missing await

### ISSUE THREAD

**Issue by navzam** [OfficeDev/BotBuilder-MicrosoftTeams-node#6]
There's a missing `await` on the `sendActivity()` here:

https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/blob/87e925af584670080677cb09f20d48f4de8797cb/samples/teams-bot/src/bot.ts#L103-L113

which results in this error:

```
(node:11052) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'set' on a proxy that has been revoked
    at adapter.sendActivities.then (C:\Users\nazam\Development\BotBuilder-MicrosoftTeams-node\botbuilder-teams-js\node_modules\botbuilder-core\src\turnContext.ts:230:63)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by robin-liao** [comment]
will fix it in next push

**Comment by navzam** [comment]
@robin-liao thanks, I submitted a PR to fix it
